/* Autogenerated by hxtools bin2c */
#ifndef WYPE_EXCLAMATION_JPG_H
#define WYPE_EXCLAMATION_JPG_H 1

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char bin2c_wype_exclamation_jpg[63304];

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* WYPE_EXCLAMATION_JPG_H */
